### ISSUE TITLE
Repeated "No trajectory defined at current time" error message when replanning

### ISSUE THREAD

**Issue by mzucker** [davetcoleman/ros_control_boilerplate#56] opened 2021-09-28 19:02 UTC
When sending overlapping trajectory snippets to the `follow_joint_trajectory` interface, occasionally there is an error message printed in red in the controller output that reads:

    Unexpected error: No trajectory defined at current time. Please contact the package maintainer.

This was first encountered with another robot controller (see <https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/470>) and reproduced with this controller as well on Ubuntu 18.04 and ROS Melodic, as well as Ubuntu 20.04 and ROS Noetic.

My two big questions about this error are

  - Is this an issue in these two particular controller implementations or is there a problem in the underlying [ros_controllers](https://github.com/ros-controls/ros_controllers) library?

  - Is this error safe to ignore, or is trajectory data being lost/ignored/changed?

I wrote a small ROS node that can reproduce the error somewhat reliably, though it is sporadic. Steps to reproduce:

  1. Clone and build the [joint_replanner](https://github.com/positronix-ai/joint_replanner/) repository.

  2. Start the rrbot simulation: 

    roslaunch ros_control_boilerplate rrbot_simulation.launch

  3. Run the replanning node:

    roslaunch joint_replanner test_rrbot.launch

After some time you will likely see the error message in the simulator launch output. If not, you can try adding load to the CPU by running a large `catkin_make` or by running the `stress` command (`sudo apt install stress`) with increasing numbers of CPU threads (e.g. `stress -cpu 4`).

Description from the joint_replanner README:

> ## What the node does
>
> This node uses the FollowJointTrajectory interface to send new trajectory snippets to the robot controller at a fixed replanning interval (e.g. 0.05 s) Each trajectory snippet starts exactly one replanning interval after the previously sent snippet, and overlaps the previous one (e.g. each is 0.20 s long). 
>
> So for example, the first trajectory snippet could go from t=0.00 to t=0.20 seconds, the second from t=0.05 to t=0.25, the third from t=0.10 to t=0.30, etc.
>
> This buffering/replanning strategy is not uncommon in robotics (e.g. receding horizon planning or [model predictive control](https://en.wikipedia.org/wiki/Model_predictive_control)).
>
> It ought to also be fully compatible with the trajectory replacement policy outlined in the [ROS wiki](http://wiki.ros.org/joint_trajectory_controller/UnderstandingTrajectoryReplacement).

There are a couple related github issues filed against the ros_controllers repo: [Issue with sample logic for joint_trajectory_controller in trajectory_interface.h #143](https://github.com/ros-controls/ros_controllers/issues/143) and [No trajectory defined at current time #312](https://github.com/ros-controls/ros_controllers/issues/312). I'll drop a breadcrumb in the 143 discussion to this issue in case it is of interest to the ros_controllers maintainers as well.

**Comment by RobertWilbrandt** [comment] 2021-10-03 15:35
Thank you for this very detailed report. To me this also looks very much like ros-controls/ros_controllers#143, especially with you mentioning that additional stress on the cpu (presumably leading to larger fluctuations in the control frequency as the controller cannot keep up) makes occurrences more likely.

In the UR repo you mention that you get these errors much more frequently with their driver than with this package. I would suspect that the reason for this is that the simulated hardware interface in this package does much less in its ```read()``` and ```write()``` functions, making fluctuations in timing less likely.

Could you turn up your logging level to ```DEBUG``` (e.g. using the ```set_logger_level``` service) and rerun this test (specifically looking for messages from the [initJointTrajectory function](https://github.com/ros-controls/ros_controllers/blob/noetic-devel/joint_trajectory_controller/include/joint_trajectory_controller/init_joint_trajectory.h#L204))? Based on the answers in the 143 discussion i suspect that this will show that the required segments get correctly inserted into the joint trajectory, meaning the problem really is in the ```joint_trajectory_controller``` update function.

**Comment by mzucker** [comment] 2021-10-04 17:54
Here's the [output](https://github.com/PickNikRobotics/ros_control_boilerplate/files/7280186/ros_log.txt) of one run that shows the error happening. Look for [ERROR] in the log. Happy to generate more if it's helpful, and appreciate any help figuring out where the issue is coming from!

**Comment by RobertWilbrandt** [comment] 2021-10-10 17:56
This really looks like 143. The trajectories seem to get added correctly

```
[DEBUG] [1633369621.478069235]: Trajectory of joint joint1has 243 segments:
- 43 segment(s) will still be executed from previous trajectory.
- 1 segment added for transitioning between the current trajectory and first point of the input message.
- 199 new segments (200 points) taken from the input trajectory.
[DEBUG] [1633369621.478667516]: Trajectory of joint joint2has 243 segments:
- 43 segment(s) will still be executed from previous trajectory.
- 1 segment added for transitioning between the current trajectory and first point of the input message.
- 199 new segments (200 points) taken from the input trajectory.
```

An the times are nicely monotonically increasing:

```
[DEBUG] [1633369621.423254921]: Using alternate time base. In it, the new trajectory starts at time 47.030
[...]
[DEBUG] [1633369621.477164357]: Using alternate time base. In it, the new trajectory starts at time 47.080
[...]
Error
[...]
[DEBUG] [1633369621.523781234]: Using alternate time base. In it, the new trajectory starts at time 47.130
```

Based on this, i guess the problem has to be solved in ```ros_controllers```. As this has to be one of the oldest still occuring ROS-issues i have seen (phew, very close to 7 years!) i would personally try to port the workaround from the fork mentioned [here](https://github.com/ros-controls/ros_controllers/issues/143#issuecomment-416251452), as the main problem in getting it merged seems to have been the lack of a reliable CI-test for it.

**Comment by mzucker** [comment] 2021-10-12 19:21
Thanks for taking a look. It's probably indeed in the lower-level code. Before I start making noise over on the ros_controllers github issues page, would you mind seeing if you can reproduce the error on one of your development setups? I don't want to hassle them if I can only see the bug on my own systems.

**Comment by RobertWilbrandt** [comment] 2021-10-21 12:26
Hey, sorry for the late reply, but after a minor sickness break i could now reproduce the problem with the steps you detailed above.

**Comment by mzucker** [comment] 2021-10-28 00:22
What's a few weeks for a 7-year old bug? :)

Thanks very much, will re-raise it on the ROS repo when I have a chance.

**Closed as completed** 2021-10-28 00:22 UTC
